// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.key_exchange.proto

package info.malenkov.aspiabook.proto;

public final class AspiaKeyExchange {
  private AspiaKeyExchange() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiabook_proto_ClientHello_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiabook_proto_ClientHello_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiabook_proto_ServerHello_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiabook_proto_ServerHello_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiabook_proto_SrpIdentify_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiabook_proto_SrpIdentify_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiabook_proto_SrpServerKeyExchange_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiabook_proto_SrpServerKeyExchange_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiabook_proto_SrpClientKeyExchange_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiabook_proto_SrpClientKeyExchange_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiabook_proto_SessionChallenge_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiabook_proto_SessionChallenge_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_malenkov_aspiabook_proto_SessionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_malenkov_aspiabook_proto_SessionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030aspia.key_exchange.proto\022\035info.malenko" +
      "v.aspiabook.proto\032\022aspia.common.proto\"|\n" +
      "\013ClientHello\022\022\n\nencryption\030\001 \001(\r\0229\n\010iden" +
      "tify\030\002 \001(\0162\'.info.malenkov.aspiabook.pro" +
      "to.Identify\022\022\n\npublic_key\030\003 \001(\014\022\n\n\002iv\030\004 " +
      "\001(\014\"X\n\013ServerHello\022=\n\nencryption\030\001 \001(\0162)" +
      ".info.malenkov.aspiabook.proto.Encryptio" +
      "n\022\n\n\002iv\030\002 \001(\014\"\037\n\013SrpIdentify\022\020\n\010username" +
      "\030\001 \001(\t\"^\n\024SrpServerKeyExchange\022\016\n\006number" +
      "\030\001 \001(\014\022\021\n\tgenerator\030\002 \001(\014\022\014\n\004salt\030\003 \001(\014\022" +
      "\t\n\001B\030\004 \001(\014\022\n\n\002iv\030\005 \001(\014\"-\n\024SrpClientKeyEx" +
      "change\022\t\n\001A\030\001 \001(\014\022\n\n\002iv\030\002 \001(\014\"\235\001\n\020Sessio" +
      "nChallenge\0227\n\007version\030\001 \001(\0132&.info.malen" +
      "kov.aspiabook.proto.Version\022\025\n\rsession_t" +
      "ypes\030\002 \001(\r\022\021\n\tcpu_cores\030\003 \001(\r\022\017\n\007os_name" +
      "\030\004 \001(\t\022\025\n\rcomputer_name\030\005 \001(\t\"\233\001\n\017Sessio" +
      "nResponse\0227\n\007version\030\001 \001(\0132&.info.malenk" +
      "ov.aspiabook.proto.Version\022\024\n\014session_ty" +
      "pe\030\002 \001(\r\022\021\n\tcpu_cores\030\003 \001(\r\022\017\n\007os_name\030\004" +
      " \001(\t\022\025\n\rcomputer_name\030\005 \001(\t*4\n\010Identify\022" +
      "\020\n\014IDENTIFY_SRP\020\000\022\026\n\022IDENTIFY_ANONYMOUS\020" +
      "\001*a\n\nEncryption\022\026\n\022ENCRYPTION_UNKNOWN\020\000\022" +
      " \n\034ENCRYPTION_CHACHA20_POLY1305\020\001\022\031\n\025ENC" +
      "RYPTION_AES256_GCM\020\002B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          info.malenkov.aspiabook.proto.AspiaCommon.getDescriptor(),
        });
    internal_static_info_malenkov_aspiabook_proto_ClientHello_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_info_malenkov_aspiabook_proto_ClientHello_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiabook_proto_ClientHello_descriptor,
        new java.lang.String[] { "Encryption", "Identify", "PublicKey", "Iv", });
    internal_static_info_malenkov_aspiabook_proto_ServerHello_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_info_malenkov_aspiabook_proto_ServerHello_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiabook_proto_ServerHello_descriptor,
        new java.lang.String[] { "Encryption", "Iv", });
    internal_static_info_malenkov_aspiabook_proto_SrpIdentify_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_info_malenkov_aspiabook_proto_SrpIdentify_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiabook_proto_SrpIdentify_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_info_malenkov_aspiabook_proto_SrpServerKeyExchange_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_info_malenkov_aspiabook_proto_SrpServerKeyExchange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiabook_proto_SrpServerKeyExchange_descriptor,
        new java.lang.String[] { "Number", "Generator", "Salt", "B", "Iv", });
    internal_static_info_malenkov_aspiabook_proto_SrpClientKeyExchange_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_info_malenkov_aspiabook_proto_SrpClientKeyExchange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiabook_proto_SrpClientKeyExchange_descriptor,
        new java.lang.String[] { "A", "Iv", });
    internal_static_info_malenkov_aspiabook_proto_SessionChallenge_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_info_malenkov_aspiabook_proto_SessionChallenge_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiabook_proto_SessionChallenge_descriptor,
        new java.lang.String[] { "Version", "SessionTypes", "CpuCores", "OsName", "ComputerName", });
    internal_static_info_malenkov_aspiabook_proto_SessionResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_info_malenkov_aspiabook_proto_SessionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_malenkov_aspiabook_proto_SessionResponse_descriptor,
        new java.lang.String[] { "Version", "SessionType", "CpuCores", "OsName", "ComputerName", });
    info.malenkov.aspiabook.proto.AspiaCommon.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
