// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.desktop.proto

package info.malenkov.aspiabook.proto;

public interface ClipboardEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:info.malenkov.aspiabook.proto.ClipboardEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string mime_type = 1;</code>
   * @return The mimeType.
   */
  java.lang.String getMimeType();
  /**
   * <code>string mime_type = 1;</code>
   * @return The bytes for mimeType.
   */
  com.google.protobuf.ByteString
      getMimeTypeBytes();

  /**
   * <code>bytes data = 2;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();
}
