// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.address_book.proto

package info.malenkov.aspiabook.proto;

public interface ComputerGroupConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:info.malenkov.aspiabook.proto.ComputerGroupConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.info.malenkov.aspiabook.proto.InheritConfig inherit = 1;</code>
   * @return Whether the inherit field is set.
   */
  boolean hasInherit();
  /**
   * <code>.info.malenkov.aspiabook.proto.InheritConfig inherit = 1;</code>
   * @return The inherit.
   */
  info.malenkov.aspiabook.proto.InheritConfig getInherit();
  /**
   * <code>.info.malenkov.aspiabook.proto.InheritConfig inherit = 1;</code>
   */
  info.malenkov.aspiabook.proto.InheritConfigOrBuilder getInheritOrBuilder();

  /**
   * <code>string username = 2;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 2;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password = 3;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 3;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>.info.malenkov.aspiabook.proto.SessionConfig session_config = 21;</code>
   * @return Whether the sessionConfig field is set.
   */
  boolean hasSessionConfig();
  /**
   * <code>.info.malenkov.aspiabook.proto.SessionConfig session_config = 21;</code>
   * @return The sessionConfig.
   */
  info.malenkov.aspiabook.proto.SessionConfig getSessionConfig();
  /**
   * <code>.info.malenkov.aspiabook.proto.SessionConfig session_config = 21;</code>
   */
  info.malenkov.aspiabook.proto.SessionConfigOrBuilder getSessionConfigOrBuilder();
}
