// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.address_book.proto

package info.malenkov.aspiabook.proto;

/**
 * Protobuf type {@code info.malenkov.aspiabook.proto.ComputerGroupConfig}
 */
public final class ComputerGroupConfig extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:info.malenkov.aspiabook.proto.ComputerGroupConfig)
    ComputerGroupConfigOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ComputerGroupConfig.newBuilder() to construct.
  private ComputerGroupConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ComputerGroupConfig() {
    username_ = "";
    password_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ComputerGroupConfig();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return info.malenkov.aspiabook.proto.AspiaAddressBook.internal_static_info_malenkov_aspiabook_proto_ComputerGroupConfig_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return info.malenkov.aspiabook.proto.AspiaAddressBook.internal_static_info_malenkov_aspiabook_proto_ComputerGroupConfig_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            info.malenkov.aspiabook.proto.ComputerGroupConfig.class, info.malenkov.aspiabook.proto.ComputerGroupConfig.Builder.class);
  }

  public static final int INHERIT_FIELD_NUMBER = 1;
  private info.malenkov.aspiabook.proto.InheritConfig inherit_;
  /**
   * <code>.info.malenkov.aspiabook.proto.InheritConfig inherit = 1;</code>
   * @return Whether the inherit field is set.
   */
  @java.lang.Override
  public boolean hasInherit() {
    return inherit_ != null;
  }
  /**
   * <code>.info.malenkov.aspiabook.proto.InheritConfig inherit = 1;</code>
   * @return The inherit.
   */
  @java.lang.Override
  public info.malenkov.aspiabook.proto.InheritConfig getInherit() {
    return inherit_ == null ? info.malenkov.aspiabook.proto.InheritConfig.getDefaultInstance() : inherit_;
  }
  /**
   * <code>.info.malenkov.aspiabook.proto.InheritConfig inherit = 1;</code>
   */
  @java.lang.Override
  public info.malenkov.aspiabook.proto.InheritConfigOrBuilder getInheritOrBuilder() {
    return inherit_ == null ? info.malenkov.aspiabook.proto.InheritConfig.getDefaultInstance() : inherit_;
  }

  public static final int USERNAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object username_ = "";
  /**
   * <code>string username = 2;</code>
   * @return The username.
   */
  @java.lang.Override
  public java.lang.String getUsername() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      username_ = s;
      return s;
    }
  }
  /**
   * <code>string username = 2;</code>
   * @return The bytes for username.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      username_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PASSWORD_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object password_ = "";
  /**
   * <code>string password = 3;</code>
   * @return The password.
   */
  @java.lang.Override
  public java.lang.String getPassword() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      password_ = s;
      return s;
    }
  }
  /**
   * <code>string password = 3;</code>
   * @return The bytes for password.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPasswordBytes() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      password_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SESSION_CONFIG_FIELD_NUMBER = 21;
  private info.malenkov.aspiabook.proto.SessionConfig sessionConfig_;
  /**
   * <code>.info.malenkov.aspiabook.proto.SessionConfig session_config = 21;</code>
   * @return Whether the sessionConfig field is set.
   */
  @java.lang.Override
  public boolean hasSessionConfig() {
    return sessionConfig_ != null;
  }
  /**
   * <code>.info.malenkov.aspiabook.proto.SessionConfig session_config = 21;</code>
   * @return The sessionConfig.
   */
  @java.lang.Override
  public info.malenkov.aspiabook.proto.SessionConfig getSessionConfig() {
    return sessionConfig_ == null ? info.malenkov.aspiabook.proto.SessionConfig.getDefaultInstance() : sessionConfig_;
  }
  /**
   * <code>.info.malenkov.aspiabook.proto.SessionConfig session_config = 21;</code>
   */
  @java.lang.Override
  public info.malenkov.aspiabook.proto.SessionConfigOrBuilder getSessionConfigOrBuilder() {
    return sessionConfig_ == null ? info.malenkov.aspiabook.proto.SessionConfig.getDefaultInstance() : sessionConfig_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (inherit_ != null) {
      output.writeMessage(1, getInherit());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(username_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, username_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, password_);
    }
    if (sessionConfig_ != null) {
      output.writeMessage(21, getSessionConfig());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (inherit_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getInherit());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(username_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, username_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, password_);
    }
    if (sessionConfig_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(21, getSessionConfig());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof info.malenkov.aspiabook.proto.ComputerGroupConfig)) {
      return super.equals(obj);
    }
    info.malenkov.aspiabook.proto.ComputerGroupConfig other = (info.malenkov.aspiabook.proto.ComputerGroupConfig) obj;

    if (hasInherit() != other.hasInherit()) return false;
    if (hasInherit()) {
      if (!getInherit()
          .equals(other.getInherit())) return false;
    }
    if (!getUsername()
        .equals(other.getUsername())) return false;
    if (!getPassword()
        .equals(other.getPassword())) return false;
    if (hasSessionConfig() != other.hasSessionConfig()) return false;
    if (hasSessionConfig()) {
      if (!getSessionConfig()
          .equals(other.getSessionConfig())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasInherit()) {
      hash = (37 * hash) + INHERIT_FIELD_NUMBER;
      hash = (53 * hash) + getInherit().hashCode();
    }
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUsername().hashCode();
    hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
    hash = (53 * hash) + getPassword().hashCode();
    if (hasSessionConfig()) {
      hash = (37 * hash) + SESSION_CONFIG_FIELD_NUMBER;
      hash = (53 * hash) + getSessionConfig().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static info.malenkov.aspiabook.proto.ComputerGroupConfig parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiabook.proto.ComputerGroupConfig parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiabook.proto.ComputerGroupConfig parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiabook.proto.ComputerGroupConfig parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiabook.proto.ComputerGroupConfig parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiabook.proto.ComputerGroupConfig parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiabook.proto.ComputerGroupConfig parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiabook.proto.ComputerGroupConfig parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static info.malenkov.aspiabook.proto.ComputerGroupConfig parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiabook.proto.ComputerGroupConfig parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static info.malenkov.aspiabook.proto.ComputerGroupConfig parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiabook.proto.ComputerGroupConfig parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(info.malenkov.aspiabook.proto.ComputerGroupConfig prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code info.malenkov.aspiabook.proto.ComputerGroupConfig}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:info.malenkov.aspiabook.proto.ComputerGroupConfig)
      info.malenkov.aspiabook.proto.ComputerGroupConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return info.malenkov.aspiabook.proto.AspiaAddressBook.internal_static_info_malenkov_aspiabook_proto_ComputerGroupConfig_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return info.malenkov.aspiabook.proto.AspiaAddressBook.internal_static_info_malenkov_aspiabook_proto_ComputerGroupConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              info.malenkov.aspiabook.proto.ComputerGroupConfig.class, info.malenkov.aspiabook.proto.ComputerGroupConfig.Builder.class);
    }

    // Construct using info.malenkov.aspiabook.proto.ComputerGroupConfig.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      inherit_ = null;
      if (inheritBuilder_ != null) {
        inheritBuilder_.dispose();
        inheritBuilder_ = null;
      }
      username_ = "";
      password_ = "";
      sessionConfig_ = null;
      if (sessionConfigBuilder_ != null) {
        sessionConfigBuilder_.dispose();
        sessionConfigBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return info.malenkov.aspiabook.proto.AspiaAddressBook.internal_static_info_malenkov_aspiabook_proto_ComputerGroupConfig_descriptor;
    }

    @java.lang.Override
    public info.malenkov.aspiabook.proto.ComputerGroupConfig getDefaultInstanceForType() {
      return info.malenkov.aspiabook.proto.ComputerGroupConfig.getDefaultInstance();
    }

    @java.lang.Override
    public info.malenkov.aspiabook.proto.ComputerGroupConfig build() {
      info.malenkov.aspiabook.proto.ComputerGroupConfig result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public info.malenkov.aspiabook.proto.ComputerGroupConfig buildPartial() {
      info.malenkov.aspiabook.proto.ComputerGroupConfig result = new info.malenkov.aspiabook.proto.ComputerGroupConfig(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(info.malenkov.aspiabook.proto.ComputerGroupConfig result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.inherit_ = inheritBuilder_ == null
            ? inherit_
            : inheritBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.username_ = username_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.password_ = password_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.sessionConfig_ = sessionConfigBuilder_ == null
            ? sessionConfig_
            : sessionConfigBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof info.malenkov.aspiabook.proto.ComputerGroupConfig) {
        return mergeFrom((info.malenkov.aspiabook.proto.ComputerGroupConfig)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(info.malenkov.aspiabook.proto.ComputerGroupConfig other) {
      if (other == info.malenkov.aspiabook.proto.ComputerGroupConfig.getDefaultInstance()) return this;
      if (other.hasInherit()) {
        mergeInherit(other.getInherit());
      }
      if (!other.getUsername().isEmpty()) {
        username_ = other.username_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getPassword().isEmpty()) {
        password_ = other.password_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.hasSessionConfig()) {
        mergeSessionConfig(other.getSessionConfig());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getInheritFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              username_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              password_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 170: {
              input.readMessage(
                  getSessionConfigFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 170
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private info.malenkov.aspiabook.proto.InheritConfig inherit_;
    private com.google.protobuf.SingleFieldBuilderV3<
        info.malenkov.aspiabook.proto.InheritConfig, info.malenkov.aspiabook.proto.InheritConfig.Builder, info.malenkov.aspiabook.proto.InheritConfigOrBuilder> inheritBuilder_;
    /**
     * <code>.info.malenkov.aspiabook.proto.InheritConfig inherit = 1;</code>
     * @return Whether the inherit field is set.
     */
    public boolean hasInherit() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.InheritConfig inherit = 1;</code>
     * @return The inherit.
     */
    public info.malenkov.aspiabook.proto.InheritConfig getInherit() {
      if (inheritBuilder_ == null) {
        return inherit_ == null ? info.malenkov.aspiabook.proto.InheritConfig.getDefaultInstance() : inherit_;
      } else {
        return inheritBuilder_.getMessage();
      }
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.InheritConfig inherit = 1;</code>
     */
    public Builder setInherit(info.malenkov.aspiabook.proto.InheritConfig value) {
      if (inheritBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        inherit_ = value;
      } else {
        inheritBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.InheritConfig inherit = 1;</code>
     */
    public Builder setInherit(
        info.malenkov.aspiabook.proto.InheritConfig.Builder builderForValue) {
      if (inheritBuilder_ == null) {
        inherit_ = builderForValue.build();
      } else {
        inheritBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.InheritConfig inherit = 1;</code>
     */
    public Builder mergeInherit(info.malenkov.aspiabook.proto.InheritConfig value) {
      if (inheritBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          inherit_ != null &&
          inherit_ != info.malenkov.aspiabook.proto.InheritConfig.getDefaultInstance()) {
          getInheritBuilder().mergeFrom(value);
        } else {
          inherit_ = value;
        }
      } else {
        inheritBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.InheritConfig inherit = 1;</code>
     */
    public Builder clearInherit() {
      bitField0_ = (bitField0_ & ~0x00000001);
      inherit_ = null;
      if (inheritBuilder_ != null) {
        inheritBuilder_.dispose();
        inheritBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.InheritConfig inherit = 1;</code>
     */
    public info.malenkov.aspiabook.proto.InheritConfig.Builder getInheritBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getInheritFieldBuilder().getBuilder();
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.InheritConfig inherit = 1;</code>
     */
    public info.malenkov.aspiabook.proto.InheritConfigOrBuilder getInheritOrBuilder() {
      if (inheritBuilder_ != null) {
        return inheritBuilder_.getMessageOrBuilder();
      } else {
        return inherit_ == null ?
            info.malenkov.aspiabook.proto.InheritConfig.getDefaultInstance() : inherit_;
      }
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.InheritConfig inherit = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        info.malenkov.aspiabook.proto.InheritConfig, info.malenkov.aspiabook.proto.InheritConfig.Builder, info.malenkov.aspiabook.proto.InheritConfigOrBuilder> 
        getInheritFieldBuilder() {
      if (inheritBuilder_ == null) {
        inheritBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            info.malenkov.aspiabook.proto.InheritConfig, info.malenkov.aspiabook.proto.InheritConfig.Builder, info.malenkov.aspiabook.proto.InheritConfigOrBuilder>(
                getInherit(),
                getParentForChildren(),
                isClean());
        inherit_ = null;
      }
      return inheritBuilder_;
    }

    private java.lang.Object username_ = "";
    /**
     * <code>string username = 2;</code>
     * @return The username.
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string username = 2;</code>
     * @return The bytes for username.
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string username = 2;</code>
     * @param value The username to set.
     * @return This builder for chaining.
     */
    public Builder setUsername(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      username_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string username = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsername() {
      username_ = getDefaultInstance().getUsername();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string username = 2;</code>
     * @param value The bytes for username to set.
     * @return This builder for chaining.
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      username_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object password_ = "";
    /**
     * <code>string password = 3;</code>
     * @return The password.
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string password = 3;</code>
     * @return The bytes for password.
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string password = 3;</code>
     * @param value The password to set.
     * @return This builder for chaining.
     */
    public Builder setPassword(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      password_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string password = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPassword() {
      password_ = getDefaultInstance().getPassword();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string password = 3;</code>
     * @param value The bytes for password to set.
     * @return This builder for chaining.
     */
    public Builder setPasswordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      password_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private info.malenkov.aspiabook.proto.SessionConfig sessionConfig_;
    private com.google.protobuf.SingleFieldBuilderV3<
        info.malenkov.aspiabook.proto.SessionConfig, info.malenkov.aspiabook.proto.SessionConfig.Builder, info.malenkov.aspiabook.proto.SessionConfigOrBuilder> sessionConfigBuilder_;
    /**
     * <code>.info.malenkov.aspiabook.proto.SessionConfig session_config = 21;</code>
     * @return Whether the sessionConfig field is set.
     */
    public boolean hasSessionConfig() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.SessionConfig session_config = 21;</code>
     * @return The sessionConfig.
     */
    public info.malenkov.aspiabook.proto.SessionConfig getSessionConfig() {
      if (sessionConfigBuilder_ == null) {
        return sessionConfig_ == null ? info.malenkov.aspiabook.proto.SessionConfig.getDefaultInstance() : sessionConfig_;
      } else {
        return sessionConfigBuilder_.getMessage();
      }
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.SessionConfig session_config = 21;</code>
     */
    public Builder setSessionConfig(info.malenkov.aspiabook.proto.SessionConfig value) {
      if (sessionConfigBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        sessionConfig_ = value;
      } else {
        sessionConfigBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.SessionConfig session_config = 21;</code>
     */
    public Builder setSessionConfig(
        info.malenkov.aspiabook.proto.SessionConfig.Builder builderForValue) {
      if (sessionConfigBuilder_ == null) {
        sessionConfig_ = builderForValue.build();
      } else {
        sessionConfigBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.SessionConfig session_config = 21;</code>
     */
    public Builder mergeSessionConfig(info.malenkov.aspiabook.proto.SessionConfig value) {
      if (sessionConfigBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          sessionConfig_ != null &&
          sessionConfig_ != info.malenkov.aspiabook.proto.SessionConfig.getDefaultInstance()) {
          getSessionConfigBuilder().mergeFrom(value);
        } else {
          sessionConfig_ = value;
        }
      } else {
        sessionConfigBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.SessionConfig session_config = 21;</code>
     */
    public Builder clearSessionConfig() {
      bitField0_ = (bitField0_ & ~0x00000008);
      sessionConfig_ = null;
      if (sessionConfigBuilder_ != null) {
        sessionConfigBuilder_.dispose();
        sessionConfigBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.SessionConfig session_config = 21;</code>
     */
    public info.malenkov.aspiabook.proto.SessionConfig.Builder getSessionConfigBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getSessionConfigFieldBuilder().getBuilder();
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.SessionConfig session_config = 21;</code>
     */
    public info.malenkov.aspiabook.proto.SessionConfigOrBuilder getSessionConfigOrBuilder() {
      if (sessionConfigBuilder_ != null) {
        return sessionConfigBuilder_.getMessageOrBuilder();
      } else {
        return sessionConfig_ == null ?
            info.malenkov.aspiabook.proto.SessionConfig.getDefaultInstance() : sessionConfig_;
      }
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.SessionConfig session_config = 21;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        info.malenkov.aspiabook.proto.SessionConfig, info.malenkov.aspiabook.proto.SessionConfig.Builder, info.malenkov.aspiabook.proto.SessionConfigOrBuilder> 
        getSessionConfigFieldBuilder() {
      if (sessionConfigBuilder_ == null) {
        sessionConfigBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            info.malenkov.aspiabook.proto.SessionConfig, info.malenkov.aspiabook.proto.SessionConfig.Builder, info.malenkov.aspiabook.proto.SessionConfigOrBuilder>(
                getSessionConfig(),
                getParentForChildren(),
                isClean());
        sessionConfig_ = null;
      }
      return sessionConfigBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:info.malenkov.aspiabook.proto.ComputerGroupConfig)
  }

  // @@protoc_insertion_point(class_scope:info.malenkov.aspiabook.proto.ComputerGroupConfig)
  private static final info.malenkov.aspiabook.proto.ComputerGroupConfig DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new info.malenkov.aspiabook.proto.ComputerGroupConfig();
  }

  public static info.malenkov.aspiabook.proto.ComputerGroupConfig getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ComputerGroupConfig>
      PARSER = new com.google.protobuf.AbstractParser<ComputerGroupConfig>() {
    @java.lang.Override
    public ComputerGroupConfig parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ComputerGroupConfig> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ComputerGroupConfig> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public info.malenkov.aspiabook.proto.ComputerGroupConfig getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

