// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.address_book.proto

package info.malenkov.aspiabook.proto;

public interface ComputerGroupOrBuilder extends
    // @@protoc_insertion_point(interface_extends:info.malenkov.aspiabook.proto.ComputerGroup)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 create_time = 1;</code>
   * @return The createTime.
   */
  long getCreateTime();

  /**
   * <code>int64 modify_time = 2;</code>
   * @return The modifyTime.
   */
  long getModifyTime();

  /**
   * <pre>
   * List of child computers.
   * </pre>
   *
   * <code>repeated .info.malenkov.aspiabook.proto.Computer computer = 3;</code>
   */
  java.util.List<info.malenkov.aspiabook.proto.Computer> 
      getComputerList();
  /**
   * <pre>
   * List of child computers.
   * </pre>
   *
   * <code>repeated .info.malenkov.aspiabook.proto.Computer computer = 3;</code>
   */
  info.malenkov.aspiabook.proto.Computer getComputer(int index);
  /**
   * <pre>
   * List of child computers.
   * </pre>
   *
   * <code>repeated .info.malenkov.aspiabook.proto.Computer computer = 3;</code>
   */
  int getComputerCount();
  /**
   * <pre>
   * List of child computers.
   * </pre>
   *
   * <code>repeated .info.malenkov.aspiabook.proto.Computer computer = 3;</code>
   */
  java.util.List<? extends info.malenkov.aspiabook.proto.ComputerOrBuilder> 
      getComputerOrBuilderList();
  /**
   * <pre>
   * List of child computers.
   * </pre>
   *
   * <code>repeated .info.malenkov.aspiabook.proto.Computer computer = 3;</code>
   */
  info.malenkov.aspiabook.proto.ComputerOrBuilder getComputerOrBuilder(
      int index);

  /**
   * <pre>
   * List of child computer groups.
   * </pre>
   *
   * <code>repeated .info.malenkov.aspiabook.proto.ComputerGroup computer_group = 4;</code>
   */
  java.util.List<info.malenkov.aspiabook.proto.ComputerGroup> 
      getComputerGroupList();
  /**
   * <pre>
   * List of child computer groups.
   * </pre>
   *
   * <code>repeated .info.malenkov.aspiabook.proto.ComputerGroup computer_group = 4;</code>
   */
  info.malenkov.aspiabook.proto.ComputerGroup getComputerGroup(int index);
  /**
   * <pre>
   * List of child computer groups.
   * </pre>
   *
   * <code>repeated .info.malenkov.aspiabook.proto.ComputerGroup computer_group = 4;</code>
   */
  int getComputerGroupCount();
  /**
   * <pre>
   * List of child computer groups.
   * </pre>
   *
   * <code>repeated .info.malenkov.aspiabook.proto.ComputerGroup computer_group = 4;</code>
   */
  java.util.List<? extends info.malenkov.aspiabook.proto.ComputerGroupOrBuilder> 
      getComputerGroupOrBuilderList();
  /**
   * <pre>
   * List of child computer groups.
   * </pre>
   *
   * <code>repeated .info.malenkov.aspiabook.proto.ComputerGroup computer_group = 4;</code>
   */
  info.malenkov.aspiabook.proto.ComputerGroupOrBuilder getComputerGroupOrBuilder(
      int index);

  /**
   * <code>string name = 5;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 5;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string comment = 6;</code>
   * @return The comment.
   */
  java.lang.String getComment();
  /**
   * <code>string comment = 6;</code>
   * @return The bytes for comment.
   */
  com.google.protobuf.ByteString
      getCommentBytes();

  /**
   * <code>bool expanded = 7;</code>
   * @return The expanded.
   */
  boolean getExpanded();

  /**
   * <code>.info.malenkov.aspiabook.proto.ComputerGroupConfig config = 21;</code>
   * @return Whether the config field is set.
   */
  boolean hasConfig();
  /**
   * <code>.info.malenkov.aspiabook.proto.ComputerGroupConfig config = 21;</code>
   * @return The config.
   */
  info.malenkov.aspiabook.proto.ComputerGroupConfig getConfig();
  /**
   * <code>.info.malenkov.aspiabook.proto.ComputerGroupConfig config = 21;</code>
   */
  info.malenkov.aspiabook.proto.ComputerGroupConfigOrBuilder getConfigOrBuilder();
}
