// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.address_book.proto

package info.malenkov.aspiabook.proto;

/**
 * Protobuf type {@code info.malenkov.aspiabook.proto.ComputerGroup}
 */
public final class ComputerGroup extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:info.malenkov.aspiabook.proto.ComputerGroup)
    ComputerGroupOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ComputerGroup.newBuilder() to construct.
  private ComputerGroup(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ComputerGroup() {
    computer_ = java.util.Collections.emptyList();
    computerGroup_ = java.util.Collections.emptyList();
    name_ = "";
    comment_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ComputerGroup();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return info.malenkov.aspiabook.proto.AspiaAddressBook.internal_static_info_malenkov_aspiabook_proto_ComputerGroup_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return info.malenkov.aspiabook.proto.AspiaAddressBook.internal_static_info_malenkov_aspiabook_proto_ComputerGroup_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            info.malenkov.aspiabook.proto.ComputerGroup.class, info.malenkov.aspiabook.proto.ComputerGroup.Builder.class);
  }

  public static final int CREATE_TIME_FIELD_NUMBER = 1;
  private long createTime_ = 0L;
  /**
   * <code>int64 create_time = 1;</code>
   * @return The createTime.
   */
  @java.lang.Override
  public long getCreateTime() {
    return createTime_;
  }

  public static final int MODIFY_TIME_FIELD_NUMBER = 2;
  private long modifyTime_ = 0L;
  /**
   * <code>int64 modify_time = 2;</code>
   * @return The modifyTime.
   */
  @java.lang.Override
  public long getModifyTime() {
    return modifyTime_;
  }

  public static final int COMPUTER_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<info.malenkov.aspiabook.proto.Computer> computer_;
  /**
   * <pre>
   * List of child computers.
   * </pre>
   *
   * <code>repeated .info.malenkov.aspiabook.proto.Computer computer = 3;</code>
   */
  @java.lang.Override
  public java.util.List<info.malenkov.aspiabook.proto.Computer> getComputerList() {
    return computer_;
  }
  /**
   * <pre>
   * List of child computers.
   * </pre>
   *
   * <code>repeated .info.malenkov.aspiabook.proto.Computer computer = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends info.malenkov.aspiabook.proto.ComputerOrBuilder> 
      getComputerOrBuilderList() {
    return computer_;
  }
  /**
   * <pre>
   * List of child computers.
   * </pre>
   *
   * <code>repeated .info.malenkov.aspiabook.proto.Computer computer = 3;</code>
   */
  @java.lang.Override
  public int getComputerCount() {
    return computer_.size();
  }
  /**
   * <pre>
   * List of child computers.
   * </pre>
   *
   * <code>repeated .info.malenkov.aspiabook.proto.Computer computer = 3;</code>
   */
  @java.lang.Override
  public info.malenkov.aspiabook.proto.Computer getComputer(int index) {
    return computer_.get(index);
  }
  /**
   * <pre>
   * List of child computers.
   * </pre>
   *
   * <code>repeated .info.malenkov.aspiabook.proto.Computer computer = 3;</code>
   */
  @java.lang.Override
  public info.malenkov.aspiabook.proto.ComputerOrBuilder getComputerOrBuilder(
      int index) {
    return computer_.get(index);
  }

  public static final int COMPUTER_GROUP_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<info.malenkov.aspiabook.proto.ComputerGroup> computerGroup_;
  /**
   * <pre>
   * List of child computer groups.
   * </pre>
   *
   * <code>repeated .info.malenkov.aspiabook.proto.ComputerGroup computer_group = 4;</code>
   */
  @java.lang.Override
  public java.util.List<info.malenkov.aspiabook.proto.ComputerGroup> getComputerGroupList() {
    return computerGroup_;
  }
  /**
   * <pre>
   * List of child computer groups.
   * </pre>
   *
   * <code>repeated .info.malenkov.aspiabook.proto.ComputerGroup computer_group = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends info.malenkov.aspiabook.proto.ComputerGroupOrBuilder> 
      getComputerGroupOrBuilderList() {
    return computerGroup_;
  }
  /**
   * <pre>
   * List of child computer groups.
   * </pre>
   *
   * <code>repeated .info.malenkov.aspiabook.proto.ComputerGroup computer_group = 4;</code>
   */
  @java.lang.Override
  public int getComputerGroupCount() {
    return computerGroup_.size();
  }
  /**
   * <pre>
   * List of child computer groups.
   * </pre>
   *
   * <code>repeated .info.malenkov.aspiabook.proto.ComputerGroup computer_group = 4;</code>
   */
  @java.lang.Override
  public info.malenkov.aspiabook.proto.ComputerGroup getComputerGroup(int index) {
    return computerGroup_.get(index);
  }
  /**
   * <pre>
   * List of child computer groups.
   * </pre>
   *
   * <code>repeated .info.malenkov.aspiabook.proto.ComputerGroup computer_group = 4;</code>
   */
  @java.lang.Override
  public info.malenkov.aspiabook.proto.ComputerGroupOrBuilder getComputerGroupOrBuilder(
      int index) {
    return computerGroup_.get(index);
  }

  public static final int NAME_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 5;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 5;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMMENT_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object comment_ = "";
  /**
   * <code>string comment = 6;</code>
   * @return The comment.
   */
  @java.lang.Override
  public java.lang.String getComment() {
    java.lang.Object ref = comment_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      comment_ = s;
      return s;
    }
  }
  /**
   * <code>string comment = 6;</code>
   * @return The bytes for comment.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCommentBytes() {
    java.lang.Object ref = comment_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      comment_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXPANDED_FIELD_NUMBER = 7;
  private boolean expanded_ = false;
  /**
   * <code>bool expanded = 7;</code>
   * @return The expanded.
   */
  @java.lang.Override
  public boolean getExpanded() {
    return expanded_;
  }

  public static final int CONFIG_FIELD_NUMBER = 21;
  private info.malenkov.aspiabook.proto.ComputerGroupConfig config_;
  /**
   * <code>.info.malenkov.aspiabook.proto.ComputerGroupConfig config = 21;</code>
   * @return Whether the config field is set.
   */
  @java.lang.Override
  public boolean hasConfig() {
    return config_ != null;
  }
  /**
   * <code>.info.malenkov.aspiabook.proto.ComputerGroupConfig config = 21;</code>
   * @return The config.
   */
  @java.lang.Override
  public info.malenkov.aspiabook.proto.ComputerGroupConfig getConfig() {
    return config_ == null ? info.malenkov.aspiabook.proto.ComputerGroupConfig.getDefaultInstance() : config_;
  }
  /**
   * <code>.info.malenkov.aspiabook.proto.ComputerGroupConfig config = 21;</code>
   */
  @java.lang.Override
  public info.malenkov.aspiabook.proto.ComputerGroupConfigOrBuilder getConfigOrBuilder() {
    return config_ == null ? info.malenkov.aspiabook.proto.ComputerGroupConfig.getDefaultInstance() : config_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (createTime_ != 0L) {
      output.writeInt64(1, createTime_);
    }
    if (modifyTime_ != 0L) {
      output.writeInt64(2, modifyTime_);
    }
    for (int i = 0; i < computer_.size(); i++) {
      output.writeMessage(3, computer_.get(i));
    }
    for (int i = 0; i < computerGroup_.size(); i++) {
      output.writeMessage(4, computerGroup_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(comment_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, comment_);
    }
    if (expanded_ != false) {
      output.writeBool(7, expanded_);
    }
    if (config_ != null) {
      output.writeMessage(21, getConfig());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (createTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, createTime_);
    }
    if (modifyTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, modifyTime_);
    }
    for (int i = 0; i < computer_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, computer_.get(i));
    }
    for (int i = 0; i < computerGroup_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, computerGroup_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(comment_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, comment_);
    }
    if (expanded_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, expanded_);
    }
    if (config_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(21, getConfig());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof info.malenkov.aspiabook.proto.ComputerGroup)) {
      return super.equals(obj);
    }
    info.malenkov.aspiabook.proto.ComputerGroup other = (info.malenkov.aspiabook.proto.ComputerGroup) obj;

    if (getCreateTime()
        != other.getCreateTime()) return false;
    if (getModifyTime()
        != other.getModifyTime()) return false;
    if (!getComputerList()
        .equals(other.getComputerList())) return false;
    if (!getComputerGroupList()
        .equals(other.getComputerGroupList())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getComment()
        .equals(other.getComment())) return false;
    if (getExpanded()
        != other.getExpanded()) return false;
    if (hasConfig() != other.hasConfig()) return false;
    if (hasConfig()) {
      if (!getConfig()
          .equals(other.getConfig())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CREATE_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCreateTime());
    hash = (37 * hash) + MODIFY_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getModifyTime());
    if (getComputerCount() > 0) {
      hash = (37 * hash) + COMPUTER_FIELD_NUMBER;
      hash = (53 * hash) + getComputerList().hashCode();
    }
    if (getComputerGroupCount() > 0) {
      hash = (37 * hash) + COMPUTER_GROUP_FIELD_NUMBER;
      hash = (53 * hash) + getComputerGroupList().hashCode();
    }
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + COMMENT_FIELD_NUMBER;
    hash = (53 * hash) + getComment().hashCode();
    hash = (37 * hash) + EXPANDED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getExpanded());
    if (hasConfig()) {
      hash = (37 * hash) + CONFIG_FIELD_NUMBER;
      hash = (53 * hash) + getConfig().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static info.malenkov.aspiabook.proto.ComputerGroup parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiabook.proto.ComputerGroup parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiabook.proto.ComputerGroup parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiabook.proto.ComputerGroup parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiabook.proto.ComputerGroup parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiabook.proto.ComputerGroup parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiabook.proto.ComputerGroup parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiabook.proto.ComputerGroup parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static info.malenkov.aspiabook.proto.ComputerGroup parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiabook.proto.ComputerGroup parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static info.malenkov.aspiabook.proto.ComputerGroup parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiabook.proto.ComputerGroup parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public Builder newBuilder(info.malenkov.aspiabook.proto.ComputerGroup prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code info.malenkov.aspiabook.proto.ComputerGroup}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:info.malenkov.aspiabook.proto.ComputerGroup)
      info.malenkov.aspiabook.proto.ComputerGroupOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return info.malenkov.aspiabook.proto.AspiaAddressBook.internal_static_info_malenkov_aspiabook_proto_ComputerGroup_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return info.malenkov.aspiabook.proto.AspiaAddressBook.internal_static_info_malenkov_aspiabook_proto_ComputerGroup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              info.malenkov.aspiabook.proto.ComputerGroup.class, info.malenkov.aspiabook.proto.ComputerGroup.Builder.class);
    }

    // Construct using info.malenkov.aspiabook.proto.ComputerGroup.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      createTime_ = 0L;
      modifyTime_ = 0L;
      if (computerBuilder_ == null) {
        computer_ = java.util.Collections.emptyList();
      } else {
        computer_ = null;
        computerBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      if (computerGroupBuilder_ == null) {
        computerGroup_ = java.util.Collections.emptyList();
      } else {
        computerGroup_ = null;
        computerGroupBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      name_ = "";
      comment_ = "";
      expanded_ = false;
      config_ = null;
      if (configBuilder_ != null) {
        configBuilder_.dispose();
        configBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return info.malenkov.aspiabook.proto.AspiaAddressBook.internal_static_info_malenkov_aspiabook_proto_ComputerGroup_descriptor;
    }

    @java.lang.Override
    public info.malenkov.aspiabook.proto.ComputerGroup getDefaultInstanceForType() {
      return info.malenkov.aspiabook.proto.ComputerGroup.getDefaultInstance();
    }

    @java.lang.Override
    public info.malenkov.aspiabook.proto.ComputerGroup build() {
      info.malenkov.aspiabook.proto.ComputerGroup result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public info.malenkov.aspiabook.proto.ComputerGroup buildPartial() {
      info.malenkov.aspiabook.proto.ComputerGroup result = new info.malenkov.aspiabook.proto.ComputerGroup(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(info.malenkov.aspiabook.proto.ComputerGroup result) {
      if (computerBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          computer_ = java.util.Collections.unmodifiableList(computer_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.computer_ = computer_;
      } else {
        result.computer_ = computerBuilder_.build();
      }
      if (computerGroupBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          computerGroup_ = java.util.Collections.unmodifiableList(computerGroup_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.computerGroup_ = computerGroup_;
      } else {
        result.computerGroup_ = computerGroupBuilder_.build();
      }
    }

    private void buildPartial0(info.malenkov.aspiabook.proto.ComputerGroup result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.createTime_ = createTime_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.modifyTime_ = modifyTime_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.comment_ = comment_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.expanded_ = expanded_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.config_ = configBuilder_ == null
            ? config_
            : configBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof info.malenkov.aspiabook.proto.ComputerGroup) {
        return mergeFrom((info.malenkov.aspiabook.proto.ComputerGroup)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(info.malenkov.aspiabook.proto.ComputerGroup other) {
      if (other == info.malenkov.aspiabook.proto.ComputerGroup.getDefaultInstance()) return this;
      if (other.getCreateTime() != 0L) {
        setCreateTime(other.getCreateTime());
      }
      if (other.getModifyTime() != 0L) {
        setModifyTime(other.getModifyTime());
      }
      if (computerBuilder_ == null) {
        if (!other.computer_.isEmpty()) {
          if (computer_.isEmpty()) {
            computer_ = other.computer_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureComputerIsMutable();
            computer_.addAll(other.computer_);
          }
          onChanged();
        }
      } else {
        if (!other.computer_.isEmpty()) {
          if (computerBuilder_.isEmpty()) {
            computerBuilder_.dispose();
            computerBuilder_ = null;
            computer_ = other.computer_;
            bitField0_ = (bitField0_ & ~0x00000004);
            computerBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getComputerFieldBuilder() : null;
          } else {
            computerBuilder_.addAllMessages(other.computer_);
          }
        }
      }
      if (computerGroupBuilder_ == null) {
        if (!other.computerGroup_.isEmpty()) {
          if (computerGroup_.isEmpty()) {
            computerGroup_ = other.computerGroup_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureComputerGroupIsMutable();
            computerGroup_.addAll(other.computerGroup_);
          }
          onChanged();
        }
      } else {
        if (!other.computerGroup_.isEmpty()) {
          if (computerGroupBuilder_.isEmpty()) {
            computerGroupBuilder_.dispose();
            computerGroupBuilder_ = null;
            computerGroup_ = other.computerGroup_;
            bitField0_ = (bitField0_ & ~0x00000008);
            computerGroupBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getComputerGroupFieldBuilder() : null;
          } else {
            computerGroupBuilder_.addAllMessages(other.computerGroup_);
          }
        }
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getComment().isEmpty()) {
        comment_ = other.comment_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.getExpanded() != false) {
        setExpanded(other.getExpanded());
      }
      if (other.hasConfig()) {
        mergeConfig(other.getConfig());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              createTime_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              modifyTime_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              info.malenkov.aspiabook.proto.Computer m =
                  input.readMessage(
                      info.malenkov.aspiabook.proto.Computer.parser(),
                      extensionRegistry);
              if (computerBuilder_ == null) {
                ensureComputerIsMutable();
                computer_.add(m);
              } else {
                computerBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 34: {
              info.malenkov.aspiabook.proto.ComputerGroup m =
                  input.readMessage(
                      info.malenkov.aspiabook.proto.ComputerGroup.parser(),
                      extensionRegistry);
              if (computerGroupBuilder_ == null) {
                ensureComputerGroupIsMutable();
                computerGroup_.add(m);
              } else {
                computerGroupBuilder_.addMessage(m);
              }
              break;
            } // case 34
            case 42: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              comment_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 56: {
              expanded_ = input.readBool();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 170: {
              input.readMessage(
                  getConfigFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000080;
              break;
            } // case 170
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long createTime_ ;
    /**
     * <code>int64 create_time = 1;</code>
     * @return The createTime.
     */
    @java.lang.Override
    public long getCreateTime() {
      return createTime_;
    }
    /**
     * <code>int64 create_time = 1;</code>
     * @param value The createTime to set.
     * @return This builder for chaining.
     */
    public Builder setCreateTime(long value) {

      createTime_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 create_time = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreateTime() {
      bitField0_ = (bitField0_ & ~0x00000001);
      createTime_ = 0L;
      onChanged();
      return this;
    }

    private long modifyTime_ ;
    /**
     * <code>int64 modify_time = 2;</code>
     * @return The modifyTime.
     */
    @java.lang.Override
    public long getModifyTime() {
      return modifyTime_;
    }
    /**
     * <code>int64 modify_time = 2;</code>
     * @param value The modifyTime to set.
     * @return This builder for chaining.
     */
    public Builder setModifyTime(long value) {

      modifyTime_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 modify_time = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearModifyTime() {
      bitField0_ = (bitField0_ & ~0x00000002);
      modifyTime_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<info.malenkov.aspiabook.proto.Computer> computer_ =
      java.util.Collections.emptyList();
    private void ensureComputerIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        computer_ = new java.util.ArrayList<info.malenkov.aspiabook.proto.Computer>(computer_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        info.malenkov.aspiabook.proto.Computer, info.malenkov.aspiabook.proto.Computer.Builder, info.malenkov.aspiabook.proto.ComputerOrBuilder> computerBuilder_;

    /**
     * <pre>
     * List of child computers.
     * </pre>
     *
     * <code>repeated .info.malenkov.aspiabook.proto.Computer computer = 3;</code>
     */
    public java.util.List<info.malenkov.aspiabook.proto.Computer> getComputerList() {
      if (computerBuilder_ == null) {
        return java.util.Collections.unmodifiableList(computer_);
      } else {
        return computerBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * List of child computers.
     * </pre>
     *
     * <code>repeated .info.malenkov.aspiabook.proto.Computer computer = 3;</code>
     */
    public int getComputerCount() {
      if (computerBuilder_ == null) {
        return computer_.size();
      } else {
        return computerBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * List of child computers.
     * </pre>
     *
     * <code>repeated .info.malenkov.aspiabook.proto.Computer computer = 3;</code>
     */
    public info.malenkov.aspiabook.proto.Computer getComputer(int index) {
      if (computerBuilder_ == null) {
        return computer_.get(index);
      } else {
        return computerBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * List of child computers.
     * </pre>
     *
     * <code>repeated .info.malenkov.aspiabook.proto.Computer computer = 3;</code>
     */
    public Builder setComputer(
        int index, info.malenkov.aspiabook.proto.Computer value) {
      if (computerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureComputerIsMutable();
        computer_.set(index, value);
        onChanged();
      } else {
        computerBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * List of child computers.
     * </pre>
     *
     * <code>repeated .info.malenkov.aspiabook.proto.Computer computer = 3;</code>
     */
    public Builder setComputer(
        int index, info.malenkov.aspiabook.proto.Computer.Builder builderForValue) {
      if (computerBuilder_ == null) {
        ensureComputerIsMutable();
        computer_.set(index, builderForValue.build());
        onChanged();
      } else {
        computerBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * List of child computers.
     * </pre>
     *
     * <code>repeated .info.malenkov.aspiabook.proto.Computer computer = 3;</code>
     */
    public Builder addComputer(info.malenkov.aspiabook.proto.Computer value) {
      if (computerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureComputerIsMutable();
        computer_.add(value);
        onChanged();
      } else {
        computerBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * List of child computers.
     * </pre>
     *
     * <code>repeated .info.malenkov.aspiabook.proto.Computer computer = 3;</code>
     */
    public Builder addComputer(
        int index, info.malenkov.aspiabook.proto.Computer value) {
      if (computerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureComputerIsMutable();
        computer_.add(index, value);
        onChanged();
      } else {
        computerBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * List of child computers.
     * </pre>
     *
     * <code>repeated .info.malenkov.aspiabook.proto.Computer computer = 3;</code>
     */
    public Builder addComputer(
        info.malenkov.aspiabook.proto.Computer.Builder builderForValue) {
      if (computerBuilder_ == null) {
        ensureComputerIsMutable();
        computer_.add(builderForValue.build());
        onChanged();
      } else {
        computerBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * List of child computers.
     * </pre>
     *
     * <code>repeated .info.malenkov.aspiabook.proto.Computer computer = 3;</code>
     */
    public Builder addComputer(
        int index, info.malenkov.aspiabook.proto.Computer.Builder builderForValue) {
      if (computerBuilder_ == null) {
        ensureComputerIsMutable();
        computer_.add(index, builderForValue.build());
        onChanged();
      } else {
        computerBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * List of child computers.
     * </pre>
     *
     * <code>repeated .info.malenkov.aspiabook.proto.Computer computer = 3;</code>
     */
    public Builder addAllComputer(
        java.lang.Iterable<? extends info.malenkov.aspiabook.proto.Computer> values) {
      if (computerBuilder_ == null) {
        ensureComputerIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, computer_);
        onChanged();
      } else {
        computerBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * List of child computers.
     * </pre>
     *
     * <code>repeated .info.malenkov.aspiabook.proto.Computer computer = 3;</code>
     */
    public Builder clearComputer() {
      if (computerBuilder_ == null) {
        computer_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        computerBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * List of child computers.
     * </pre>
     *
     * <code>repeated .info.malenkov.aspiabook.proto.Computer computer = 3;</code>
     */
    public Builder removeComputer(int index) {
      if (computerBuilder_ == null) {
        ensureComputerIsMutable();
        computer_.remove(index);
        onChanged();
      } else {
        computerBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * List of child computers.
     * </pre>
     *
     * <code>repeated .info.malenkov.aspiabook.proto.Computer computer = 3;</code>
     */
    public info.malenkov.aspiabook.proto.Computer.Builder getComputerBuilder(
        int index) {
      return getComputerFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * List of child computers.
     * </pre>
     *
     * <code>repeated .info.malenkov.aspiabook.proto.Computer computer = 3;</code>
     */
    public info.malenkov.aspiabook.proto.ComputerOrBuilder getComputerOrBuilder(
        int index) {
      if (computerBuilder_ == null) {
        return computer_.get(index);  } else {
        return computerBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * List of child computers.
     * </pre>
     *
     * <code>repeated .info.malenkov.aspiabook.proto.Computer computer = 3;</code>
     */
    public java.util.List<? extends info.malenkov.aspiabook.proto.ComputerOrBuilder> 
         getComputerOrBuilderList() {
      if (computerBuilder_ != null) {
        return computerBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(computer_);
      }
    }
    /**
     * <pre>
     * List of child computers.
     * </pre>
     *
     * <code>repeated .info.malenkov.aspiabook.proto.Computer computer = 3;</code>
     */
    public info.malenkov.aspiabook.proto.Computer.Builder addComputerBuilder() {
      return getComputerFieldBuilder().addBuilder(
          info.malenkov.aspiabook.proto.Computer.getDefaultInstance());
    }
    /**
     * <pre>
     * List of child computers.
     * </pre>
     *
     * <code>repeated .info.malenkov.aspiabook.proto.Computer computer = 3;</code>
     */
    public info.malenkov.aspiabook.proto.Computer.Builder addComputerBuilder(
        int index) {
      return getComputerFieldBuilder().addBuilder(
          index, info.malenkov.aspiabook.proto.Computer.getDefaultInstance());
    }
    /**
     * <pre>
     * List of child computers.
     * </pre>
     *
     * <code>repeated .info.malenkov.aspiabook.proto.Computer computer = 3;</code>
     */
    public java.util.List<info.malenkov.aspiabook.proto.Computer.Builder> 
         getComputerBuilderList() {
      return getComputerFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        info.malenkov.aspiabook.proto.Computer, info.malenkov.aspiabook.proto.Computer.Builder, info.malenkov.aspiabook.proto.ComputerOrBuilder> 
        getComputerFieldBuilder() {
      if (computerBuilder_ == null) {
        computerBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            info.malenkov.aspiabook.proto.Computer, info.malenkov.aspiabook.proto.Computer.Builder, info.malenkov.aspiabook.proto.ComputerOrBuilder>(
                computer_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        computer_ = null;
      }
      return computerBuilder_;
    }

    private java.util.List<info.malenkov.aspiabook.proto.ComputerGroup> computerGroup_ =
      java.util.Collections.emptyList();
    private void ensureComputerGroupIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        computerGroup_ = new java.util.ArrayList<info.malenkov.aspiabook.proto.ComputerGroup>(computerGroup_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        info.malenkov.aspiabook.proto.ComputerGroup, info.malenkov.aspiabook.proto.ComputerGroup.Builder, info.malenkov.aspiabook.proto.ComputerGroupOrBuilder> computerGroupBuilder_;

    /**
     * <pre>
     * List of child computer groups.
     * </pre>
     *
     * <code>repeated .info.malenkov.aspiabook.proto.ComputerGroup computer_group = 4;</code>
     */
    public java.util.List<info.malenkov.aspiabook.proto.ComputerGroup> getComputerGroupList() {
      if (computerGroupBuilder_ == null) {
        return java.util.Collections.unmodifiableList(computerGroup_);
      } else {
        return computerGroupBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * List of child computer groups.
     * </pre>
     *
     * <code>repeated .info.malenkov.aspiabook.proto.ComputerGroup computer_group = 4;</code>
     */
    public int getComputerGroupCount() {
      if (computerGroupBuilder_ == null) {
        return computerGroup_.size();
      } else {
        return computerGroupBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * List of child computer groups.
     * </pre>
     *
     * <code>repeated .info.malenkov.aspiabook.proto.ComputerGroup computer_group = 4;</code>
     */
    public info.malenkov.aspiabook.proto.ComputerGroup getComputerGroup(int index) {
      if (computerGroupBuilder_ == null) {
        return computerGroup_.get(index);
      } else {
        return computerGroupBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * List of child computer groups.
     * </pre>
     *
     * <code>repeated .info.malenkov.aspiabook.proto.ComputerGroup computer_group = 4;</code>
     */
    public Builder setComputerGroup(
        int index, info.malenkov.aspiabook.proto.ComputerGroup value) {
      if (computerGroupBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureComputerGroupIsMutable();
        computerGroup_.set(index, value);
        onChanged();
      } else {
        computerGroupBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * List of child computer groups.
     * </pre>
     *
     * <code>repeated .info.malenkov.aspiabook.proto.ComputerGroup computer_group = 4;</code>
     */
    public Builder setComputerGroup(
        int index, info.malenkov.aspiabook.proto.ComputerGroup.Builder builderForValue) {
      if (computerGroupBuilder_ == null) {
        ensureComputerGroupIsMutable();
        computerGroup_.set(index, builderForValue.build());
        onChanged();
      } else {
        computerGroupBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * List of child computer groups.
     * </pre>
     *
     * <code>repeated .info.malenkov.aspiabook.proto.ComputerGroup computer_group = 4;</code>
     */
    public Builder addComputerGroup(info.malenkov.aspiabook.proto.ComputerGroup value) {
      if (computerGroupBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureComputerGroupIsMutable();
        computerGroup_.add(value);
        onChanged();
      } else {
        computerGroupBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * List of child computer groups.
     * </pre>
     *
     * <code>repeated .info.malenkov.aspiabook.proto.ComputerGroup computer_group = 4;</code>
     */
    public Builder addComputerGroup(
        int index, info.malenkov.aspiabook.proto.ComputerGroup value) {
      if (computerGroupBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureComputerGroupIsMutable();
        computerGroup_.add(index, value);
        onChanged();
      } else {
        computerGroupBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * List of child computer groups.
     * </pre>
     *
     * <code>repeated .info.malenkov.aspiabook.proto.ComputerGroup computer_group = 4;</code>
     */
    public Builder addComputerGroup(
        info.malenkov.aspiabook.proto.ComputerGroup.Builder builderForValue) {
      if (computerGroupBuilder_ == null) {
        ensureComputerGroupIsMutable();
        computerGroup_.add(builderForValue.build());
        onChanged();
      } else {
        computerGroupBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * List of child computer groups.
     * </pre>
     *
     * <code>repeated .info.malenkov.aspiabook.proto.ComputerGroup computer_group = 4;</code>
     */
    public Builder addComputerGroup(
        int index, info.malenkov.aspiabook.proto.ComputerGroup.Builder builderForValue) {
      if (computerGroupBuilder_ == null) {
        ensureComputerGroupIsMutable();
        computerGroup_.add(index, builderForValue.build());
        onChanged();
      } else {
        computerGroupBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * List of child computer groups.
     * </pre>
     *
     * <code>repeated .info.malenkov.aspiabook.proto.ComputerGroup computer_group = 4;</code>
     */
    public Builder addAllComputerGroup(
        java.lang.Iterable<? extends info.malenkov.aspiabook.proto.ComputerGroup> values) {
      if (computerGroupBuilder_ == null) {
        ensureComputerGroupIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, computerGroup_);
        onChanged();
      } else {
        computerGroupBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * List of child computer groups.
     * </pre>
     *
     * <code>repeated .info.malenkov.aspiabook.proto.ComputerGroup computer_group = 4;</code>
     */
    public Builder clearComputerGroup() {
      if (computerGroupBuilder_ == null) {
        computerGroup_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        computerGroupBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * List of child computer groups.
     * </pre>
     *
     * <code>repeated .info.malenkov.aspiabook.proto.ComputerGroup computer_group = 4;</code>
     */
    public Builder removeComputerGroup(int index) {
      if (computerGroupBuilder_ == null) {
        ensureComputerGroupIsMutable();
        computerGroup_.remove(index);
        onChanged();
      } else {
        computerGroupBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * List of child computer groups.
     * </pre>
     *
     * <code>repeated .info.malenkov.aspiabook.proto.ComputerGroup computer_group = 4;</code>
     */
    public info.malenkov.aspiabook.proto.ComputerGroup.Builder getComputerGroupBuilder(
        int index) {
      return getComputerGroupFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * List of child computer groups.
     * </pre>
     *
     * <code>repeated .info.malenkov.aspiabook.proto.ComputerGroup computer_group = 4;</code>
     */
    public info.malenkov.aspiabook.proto.ComputerGroupOrBuilder getComputerGroupOrBuilder(
        int index) {
      if (computerGroupBuilder_ == null) {
        return computerGroup_.get(index);  } else {
        return computerGroupBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * List of child computer groups.
     * </pre>
     *
     * <code>repeated .info.malenkov.aspiabook.proto.ComputerGroup computer_group = 4;</code>
     */
    public java.util.List<? extends info.malenkov.aspiabook.proto.ComputerGroupOrBuilder> 
         getComputerGroupOrBuilderList() {
      if (computerGroupBuilder_ != null) {
        return computerGroupBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(computerGroup_);
      }
    }
    /**
     * <pre>
     * List of child computer groups.
     * </pre>
     *
     * <code>repeated .info.malenkov.aspiabook.proto.ComputerGroup computer_group = 4;</code>
     */
    public info.malenkov.aspiabook.proto.ComputerGroup.Builder addComputerGroupBuilder() {
      return getComputerGroupFieldBuilder().addBuilder(
          info.malenkov.aspiabook.proto.ComputerGroup.getDefaultInstance());
    }
    /**
     * <pre>
     * List of child computer groups.
     * </pre>
     *
     * <code>repeated .info.malenkov.aspiabook.proto.ComputerGroup computer_group = 4;</code>
     */
    public info.malenkov.aspiabook.proto.ComputerGroup.Builder addComputerGroupBuilder(
        int index) {
      return getComputerGroupFieldBuilder().addBuilder(
          index, info.malenkov.aspiabook.proto.ComputerGroup.getDefaultInstance());
    }
    /**
     * <pre>
     * List of child computer groups.
     * </pre>
     *
     * <code>repeated .info.malenkov.aspiabook.proto.ComputerGroup computer_group = 4;</code>
     */
    public java.util.List<info.malenkov.aspiabook.proto.ComputerGroup.Builder> 
         getComputerGroupBuilderList() {
      return getComputerGroupFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        info.malenkov.aspiabook.proto.ComputerGroup, info.malenkov.aspiabook.proto.ComputerGroup.Builder, info.malenkov.aspiabook.proto.ComputerGroupOrBuilder> 
        getComputerGroupFieldBuilder() {
      if (computerGroupBuilder_ == null) {
        computerGroupBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            info.malenkov.aspiabook.proto.ComputerGroup, info.malenkov.aspiabook.proto.ComputerGroup.Builder, info.malenkov.aspiabook.proto.ComputerGroupOrBuilder>(
                computerGroup_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        computerGroup_ = null;
      }
      return computerGroupBuilder_;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 5;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 5;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 5;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 5;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object comment_ = "";
    /**
     * <code>string comment = 6;</code>
     * @return The comment.
     */
    public java.lang.String getComment() {
      java.lang.Object ref = comment_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        comment_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string comment = 6;</code>
     * @return The bytes for comment.
     */
    public com.google.protobuf.ByteString
        getCommentBytes() {
      java.lang.Object ref = comment_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        comment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string comment = 6;</code>
     * @param value The comment to set.
     * @return This builder for chaining.
     */
    public Builder setComment(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      comment_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string comment = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearComment() {
      comment_ = getDefaultInstance().getComment();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string comment = 6;</code>
     * @param value The bytes for comment to set.
     * @return This builder for chaining.
     */
    public Builder setCommentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      comment_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private boolean expanded_ ;
    /**
     * <code>bool expanded = 7;</code>
     * @return The expanded.
     */
    @java.lang.Override
    public boolean getExpanded() {
      return expanded_;
    }
    /**
     * <code>bool expanded = 7;</code>
     * @param value The expanded to set.
     * @return This builder for chaining.
     */
    public Builder setExpanded(boolean value) {

      expanded_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>bool expanded = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearExpanded() {
      bitField0_ = (bitField0_ & ~0x00000040);
      expanded_ = false;
      onChanged();
      return this;
    }

    private info.malenkov.aspiabook.proto.ComputerGroupConfig config_;
    private com.google.protobuf.SingleFieldBuilderV3<
        info.malenkov.aspiabook.proto.ComputerGroupConfig, info.malenkov.aspiabook.proto.ComputerGroupConfig.Builder, info.malenkov.aspiabook.proto.ComputerGroupConfigOrBuilder> configBuilder_;
    /**
     * <code>.info.malenkov.aspiabook.proto.ComputerGroupConfig config = 21;</code>
     * @return Whether the config field is set.
     */
    public boolean hasConfig() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.ComputerGroupConfig config = 21;</code>
     * @return The config.
     */
    public info.malenkov.aspiabook.proto.ComputerGroupConfig getConfig() {
      if (configBuilder_ == null) {
        return config_ == null ? info.malenkov.aspiabook.proto.ComputerGroupConfig.getDefaultInstance() : config_;
      } else {
        return configBuilder_.getMessage();
      }
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.ComputerGroupConfig config = 21;</code>
     */
    public Builder setConfig(info.malenkov.aspiabook.proto.ComputerGroupConfig value) {
      if (configBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        config_ = value;
      } else {
        configBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.ComputerGroupConfig config = 21;</code>
     */
    public Builder setConfig(
        info.malenkov.aspiabook.proto.ComputerGroupConfig.Builder builderForValue) {
      if (configBuilder_ == null) {
        config_ = builderForValue.build();
      } else {
        configBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.ComputerGroupConfig config = 21;</code>
     */
    public Builder mergeConfig(info.malenkov.aspiabook.proto.ComputerGroupConfig value) {
      if (configBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0) &&
          config_ != null &&
          config_ != info.malenkov.aspiabook.proto.ComputerGroupConfig.getDefaultInstance()) {
          getConfigBuilder().mergeFrom(value);
        } else {
          config_ = value;
        }
      } else {
        configBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.ComputerGroupConfig config = 21;</code>
     */
    public Builder clearConfig() {
      bitField0_ = (bitField0_ & ~0x00000080);
      config_ = null;
      if (configBuilder_ != null) {
        configBuilder_.dispose();
        configBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.ComputerGroupConfig config = 21;</code>
     */
    public info.malenkov.aspiabook.proto.ComputerGroupConfig.Builder getConfigBuilder() {
      bitField0_ |= 0x00000080;
      onChanged();
      return getConfigFieldBuilder().getBuilder();
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.ComputerGroupConfig config = 21;</code>
     */
    public info.malenkov.aspiabook.proto.ComputerGroupConfigOrBuilder getConfigOrBuilder() {
      if (configBuilder_ != null) {
        return configBuilder_.getMessageOrBuilder();
      } else {
        return config_ == null ?
            info.malenkov.aspiabook.proto.ComputerGroupConfig.getDefaultInstance() : config_;
      }
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.ComputerGroupConfig config = 21;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        info.malenkov.aspiabook.proto.ComputerGroupConfig, info.malenkov.aspiabook.proto.ComputerGroupConfig.Builder, info.malenkov.aspiabook.proto.ComputerGroupConfigOrBuilder> 
        getConfigFieldBuilder() {
      if (configBuilder_ == null) {
        configBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            info.malenkov.aspiabook.proto.ComputerGroupConfig, info.malenkov.aspiabook.proto.ComputerGroupConfig.Builder, info.malenkov.aspiabook.proto.ComputerGroupConfigOrBuilder>(
                getConfig(),
                getParentForChildren(),
                isClean());
        config_ = null;
      }
      return configBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:info.malenkov.aspiabook.proto.ComputerGroup)
  }

  // @@protoc_insertion_point(class_scope:info.malenkov.aspiabook.proto.ComputerGroup)
  private static final info.malenkov.aspiabook.proto.ComputerGroup DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new info.malenkov.aspiabook.proto.ComputerGroup();
  }

  public static info.malenkov.aspiabook.proto.ComputerGroup getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ComputerGroup>
      PARSER = new com.google.protobuf.AbstractParser<ComputerGroup>() {
    @java.lang.Override
    public ComputerGroup parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ComputerGroup> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ComputerGroup> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public info.malenkov.aspiabook.proto.ComputerGroup getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

