// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.desktop.proto

package info.malenkov.aspiabook.proto;

/**
 * Protobuf type {@code info.malenkov.aspiabook.proto.DesktopConfig}
 */
public final class DesktopConfig extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:info.malenkov.aspiabook.proto.DesktopConfig)
    DesktopConfigOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DesktopConfig.newBuilder() to construct.
  private DesktopConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DesktopConfig() {
    videoEncoding_ = 0;
    audioEncoding_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DesktopConfig();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return info.malenkov.aspiabook.proto.AspiaDesktop.internal_static_info_malenkov_aspiabook_proto_DesktopConfig_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return info.malenkov.aspiabook.proto.AspiaDesktop.internal_static_info_malenkov_aspiabook_proto_DesktopConfig_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            info.malenkov.aspiabook.proto.DesktopConfig.class, info.malenkov.aspiabook.proto.DesktopConfig.Builder.class);
  }

  public static final int FLAGS_FIELD_NUMBER = 1;
  private int flags_ = 0;
  /**
   * <code>uint32 flags = 1;</code>
   * @return The flags.
   */
  @java.lang.Override
  public int getFlags() {
    return flags_;
  }

  public static final int VIDEO_ENCODING_FIELD_NUMBER = 2;
  private int videoEncoding_ = 0;
  /**
   * <code>.info.malenkov.aspiabook.proto.VideoEncoding video_encoding = 2;</code>
   * @return The enum numeric value on the wire for videoEncoding.
   */
  @java.lang.Override public int getVideoEncodingValue() {
    return videoEncoding_;
  }
  /**
   * <code>.info.malenkov.aspiabook.proto.VideoEncoding video_encoding = 2;</code>
   * @return The videoEncoding.
   */
  @java.lang.Override public info.malenkov.aspiabook.proto.VideoEncoding getVideoEncoding() {
    info.malenkov.aspiabook.proto.VideoEncoding result = info.malenkov.aspiabook.proto.VideoEncoding.forNumber(videoEncoding_);
    return result == null ? info.malenkov.aspiabook.proto.VideoEncoding.UNRECOGNIZED : result;
  }

  public static final int PIXEL_FORMAT_FIELD_NUMBER = 3;
  private info.malenkov.aspiabook.proto.PixelFormat pixelFormat_;
  /**
   * <code>.info.malenkov.aspiabook.proto.PixelFormat pixel_format = 3;</code>
   * @return Whether the pixelFormat field is set.
   */
  @java.lang.Override
  public boolean hasPixelFormat() {
    return pixelFormat_ != null;
  }
  /**
   * <code>.info.malenkov.aspiabook.proto.PixelFormat pixel_format = 3;</code>
   * @return The pixelFormat.
   */
  @java.lang.Override
  public info.malenkov.aspiabook.proto.PixelFormat getPixelFormat() {
    return pixelFormat_ == null ? info.malenkov.aspiabook.proto.PixelFormat.getDefaultInstance() : pixelFormat_;
  }
  /**
   * <code>.info.malenkov.aspiabook.proto.PixelFormat pixel_format = 3;</code>
   */
  @java.lang.Override
  public info.malenkov.aspiabook.proto.PixelFormatOrBuilder getPixelFormatOrBuilder() {
    return pixelFormat_ == null ? info.malenkov.aspiabook.proto.PixelFormat.getDefaultInstance() : pixelFormat_;
  }

  public static final int UPDATE_INTERVAL_FIELD_NUMBER = 4;
  private int updateInterval_ = 0;
  /**
   * <pre>
   * Deprecated. Must be equal to 30.
   * </pre>
   *
   * <code>uint32 update_interval = 4;</code>
   * @return The updateInterval.
   */
  @java.lang.Override
  public int getUpdateInterval() {
    return updateInterval_;
  }

  public static final int COMPRESS_RATIO_FIELD_NUMBER = 5;
  private int compressRatio_ = 0;
  /**
   * <code>uint32 compress_ratio = 5;</code>
   * @return The compressRatio.
   */
  @java.lang.Override
  public int getCompressRatio() {
    return compressRatio_;
  }

  public static final int SCALE_FACTOR_FIELD_NUMBER = 6;
  private int scaleFactor_ = 0;
  /**
   * <pre>
   * Deprecated. Must be equal to 100.
   * </pre>
   *
   * <code>uint32 scale_factor = 6;</code>
   * @return The scaleFactor.
   */
  @java.lang.Override
  public int getScaleFactor() {
    return scaleFactor_;
  }

  public static final int AUDIO_ENCODING_FIELD_NUMBER = 7;
  private int audioEncoding_ = 0;
  /**
   * <code>.info.malenkov.aspiabook.proto.AudioEncoding audio_encoding = 7;</code>
   * @return The enum numeric value on the wire for audioEncoding.
   */
  @java.lang.Override public int getAudioEncodingValue() {
    return audioEncoding_;
  }
  /**
   * <code>.info.malenkov.aspiabook.proto.AudioEncoding audio_encoding = 7;</code>
   * @return The audioEncoding.
   */
  @java.lang.Override public info.malenkov.aspiabook.proto.AudioEncoding getAudioEncoding() {
    info.malenkov.aspiabook.proto.AudioEncoding result = info.malenkov.aspiabook.proto.AudioEncoding.forNumber(audioEncoding_);
    return result == null ? info.malenkov.aspiabook.proto.AudioEncoding.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (flags_ != 0) {
      output.writeUInt32(1, flags_);
    }
    if (videoEncoding_ != info.malenkov.aspiabook.proto.VideoEncoding.VIDEO_ENCODING_UNKNOWN.getNumber()) {
      output.writeEnum(2, videoEncoding_);
    }
    if (pixelFormat_ != null) {
      output.writeMessage(3, getPixelFormat());
    }
    if (updateInterval_ != 0) {
      output.writeUInt32(4, updateInterval_);
    }
    if (compressRatio_ != 0) {
      output.writeUInt32(5, compressRatio_);
    }
    if (scaleFactor_ != 0) {
      output.writeUInt32(6, scaleFactor_);
    }
    if (audioEncoding_ != info.malenkov.aspiabook.proto.AudioEncoding.AUDIO_ENCODING_UNKNOWN.getNumber()) {
      output.writeEnum(7, audioEncoding_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (flags_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, flags_);
    }
    if (videoEncoding_ != info.malenkov.aspiabook.proto.VideoEncoding.VIDEO_ENCODING_UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, videoEncoding_);
    }
    if (pixelFormat_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getPixelFormat());
    }
    if (updateInterval_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, updateInterval_);
    }
    if (compressRatio_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, compressRatio_);
    }
    if (scaleFactor_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(6, scaleFactor_);
    }
    if (audioEncoding_ != info.malenkov.aspiabook.proto.AudioEncoding.AUDIO_ENCODING_UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, audioEncoding_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof info.malenkov.aspiabook.proto.DesktopConfig)) {
      return super.equals(obj);
    }
    info.malenkov.aspiabook.proto.DesktopConfig other = (info.malenkov.aspiabook.proto.DesktopConfig) obj;

    if (getFlags()
        != other.getFlags()) return false;
    if (videoEncoding_ != other.videoEncoding_) return false;
    if (hasPixelFormat() != other.hasPixelFormat()) return false;
    if (hasPixelFormat()) {
      if (!getPixelFormat()
          .equals(other.getPixelFormat())) return false;
    }
    if (getUpdateInterval()
        != other.getUpdateInterval()) return false;
    if (getCompressRatio()
        != other.getCompressRatio()) return false;
    if (getScaleFactor()
        != other.getScaleFactor()) return false;
    if (audioEncoding_ != other.audioEncoding_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FLAGS_FIELD_NUMBER;
    hash = (53 * hash) + getFlags();
    hash = (37 * hash) + VIDEO_ENCODING_FIELD_NUMBER;
    hash = (53 * hash) + videoEncoding_;
    if (hasPixelFormat()) {
      hash = (37 * hash) + PIXEL_FORMAT_FIELD_NUMBER;
      hash = (53 * hash) + getPixelFormat().hashCode();
    }
    hash = (37 * hash) + UPDATE_INTERVAL_FIELD_NUMBER;
    hash = (53 * hash) + getUpdateInterval();
    hash = (37 * hash) + COMPRESS_RATIO_FIELD_NUMBER;
    hash = (53 * hash) + getCompressRatio();
    hash = (37 * hash) + SCALE_FACTOR_FIELD_NUMBER;
    hash = (53 * hash) + getScaleFactor();
    hash = (37 * hash) + AUDIO_ENCODING_FIELD_NUMBER;
    hash = (53 * hash) + audioEncoding_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static info.malenkov.aspiabook.proto.DesktopConfig parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiabook.proto.DesktopConfig parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiabook.proto.DesktopConfig parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiabook.proto.DesktopConfig parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiabook.proto.DesktopConfig parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiabook.proto.DesktopConfig parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiabook.proto.DesktopConfig parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiabook.proto.DesktopConfig parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static info.malenkov.aspiabook.proto.DesktopConfig parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiabook.proto.DesktopConfig parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static info.malenkov.aspiabook.proto.DesktopConfig parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiabook.proto.DesktopConfig parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(info.malenkov.aspiabook.proto.DesktopConfig prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code info.malenkov.aspiabook.proto.DesktopConfig}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:info.malenkov.aspiabook.proto.DesktopConfig)
      info.malenkov.aspiabook.proto.DesktopConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return info.malenkov.aspiabook.proto.AspiaDesktop.internal_static_info_malenkov_aspiabook_proto_DesktopConfig_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return info.malenkov.aspiabook.proto.AspiaDesktop.internal_static_info_malenkov_aspiabook_proto_DesktopConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              info.malenkov.aspiabook.proto.DesktopConfig.class, info.malenkov.aspiabook.proto.DesktopConfig.Builder.class);
    }

    // Construct using info.malenkov.aspiabook.proto.DesktopConfig.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      flags_ = 0;
      videoEncoding_ = 0;
      pixelFormat_ = null;
      if (pixelFormatBuilder_ != null) {
        pixelFormatBuilder_.dispose();
        pixelFormatBuilder_ = null;
      }
      updateInterval_ = 0;
      compressRatio_ = 0;
      scaleFactor_ = 0;
      audioEncoding_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return info.malenkov.aspiabook.proto.AspiaDesktop.internal_static_info_malenkov_aspiabook_proto_DesktopConfig_descriptor;
    }

    @java.lang.Override
    public info.malenkov.aspiabook.proto.DesktopConfig getDefaultInstanceForType() {
      return info.malenkov.aspiabook.proto.DesktopConfig.getDefaultInstance();
    }

    @java.lang.Override
    public info.malenkov.aspiabook.proto.DesktopConfig build() {
      info.malenkov.aspiabook.proto.DesktopConfig result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public info.malenkov.aspiabook.proto.DesktopConfig buildPartial() {
      info.malenkov.aspiabook.proto.DesktopConfig result = new info.malenkov.aspiabook.proto.DesktopConfig(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(info.malenkov.aspiabook.proto.DesktopConfig result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.flags_ = flags_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.videoEncoding_ = videoEncoding_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.pixelFormat_ = pixelFormatBuilder_ == null
            ? pixelFormat_
            : pixelFormatBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.updateInterval_ = updateInterval_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.compressRatio_ = compressRatio_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.scaleFactor_ = scaleFactor_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.audioEncoding_ = audioEncoding_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof info.malenkov.aspiabook.proto.DesktopConfig) {
        return mergeFrom((info.malenkov.aspiabook.proto.DesktopConfig)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(info.malenkov.aspiabook.proto.DesktopConfig other) {
      if (other == info.malenkov.aspiabook.proto.DesktopConfig.getDefaultInstance()) return this;
      if (other.getFlags() != 0) {
        setFlags(other.getFlags());
      }
      if (other.videoEncoding_ != 0) {
        setVideoEncodingValue(other.getVideoEncodingValue());
      }
      if (other.hasPixelFormat()) {
        mergePixelFormat(other.getPixelFormat());
      }
      if (other.getUpdateInterval() != 0) {
        setUpdateInterval(other.getUpdateInterval());
      }
      if (other.getCompressRatio() != 0) {
        setCompressRatio(other.getCompressRatio());
      }
      if (other.getScaleFactor() != 0) {
        setScaleFactor(other.getScaleFactor());
      }
      if (other.audioEncoding_ != 0) {
        setAudioEncodingValue(other.getAudioEncodingValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              flags_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              videoEncoding_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              input.readMessage(
                  getPixelFormatFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              updateInterval_ = input.readUInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              compressRatio_ = input.readUInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              scaleFactor_ = input.readUInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              audioEncoding_ = input.readEnum();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int flags_ ;
    /**
     * <code>uint32 flags = 1;</code>
     * @return The flags.
     */
    @java.lang.Override
    public int getFlags() {
      return flags_;
    }
    /**
     * <code>uint32 flags = 1;</code>
     * @param value The flags to set.
     * @return This builder for chaining.
     */
    public Builder setFlags(int value) {

      flags_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 flags = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFlags() {
      bitField0_ = (bitField0_ & ~0x00000001);
      flags_ = 0;
      onChanged();
      return this;
    }

    private int videoEncoding_ = 0;
    /**
     * <code>.info.malenkov.aspiabook.proto.VideoEncoding video_encoding = 2;</code>
     * @return The enum numeric value on the wire for videoEncoding.
     */
    @java.lang.Override public int getVideoEncodingValue() {
      return videoEncoding_;
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.VideoEncoding video_encoding = 2;</code>
     * @param value The enum numeric value on the wire for videoEncoding to set.
     * @return This builder for chaining.
     */
    public Builder setVideoEncodingValue(int value) {
      videoEncoding_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.VideoEncoding video_encoding = 2;</code>
     * @return The videoEncoding.
     */
    @java.lang.Override
    public info.malenkov.aspiabook.proto.VideoEncoding getVideoEncoding() {
      info.malenkov.aspiabook.proto.VideoEncoding result = info.malenkov.aspiabook.proto.VideoEncoding.forNumber(videoEncoding_);
      return result == null ? info.malenkov.aspiabook.proto.VideoEncoding.UNRECOGNIZED : result;
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.VideoEncoding video_encoding = 2;</code>
     * @param value The videoEncoding to set.
     * @return This builder for chaining.
     */
    public Builder setVideoEncoding(info.malenkov.aspiabook.proto.VideoEncoding value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      videoEncoding_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.VideoEncoding video_encoding = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearVideoEncoding() {
      bitField0_ = (bitField0_ & ~0x00000002);
      videoEncoding_ = 0;
      onChanged();
      return this;
    }

    private info.malenkov.aspiabook.proto.PixelFormat pixelFormat_;
    private com.google.protobuf.SingleFieldBuilderV3<
        info.malenkov.aspiabook.proto.PixelFormat, info.malenkov.aspiabook.proto.PixelFormat.Builder, info.malenkov.aspiabook.proto.PixelFormatOrBuilder> pixelFormatBuilder_;
    /**
     * <code>.info.malenkov.aspiabook.proto.PixelFormat pixel_format = 3;</code>
     * @return Whether the pixelFormat field is set.
     */
    public boolean hasPixelFormat() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.PixelFormat pixel_format = 3;</code>
     * @return The pixelFormat.
     */
    public info.malenkov.aspiabook.proto.PixelFormat getPixelFormat() {
      if (pixelFormatBuilder_ == null) {
        return pixelFormat_ == null ? info.malenkov.aspiabook.proto.PixelFormat.getDefaultInstance() : pixelFormat_;
      } else {
        return pixelFormatBuilder_.getMessage();
      }
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.PixelFormat pixel_format = 3;</code>
     */
    public Builder setPixelFormat(info.malenkov.aspiabook.proto.PixelFormat value) {
      if (pixelFormatBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pixelFormat_ = value;
      } else {
        pixelFormatBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.PixelFormat pixel_format = 3;</code>
     */
    public Builder setPixelFormat(
        info.malenkov.aspiabook.proto.PixelFormat.Builder builderForValue) {
      if (pixelFormatBuilder_ == null) {
        pixelFormat_ = builderForValue.build();
      } else {
        pixelFormatBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.PixelFormat pixel_format = 3;</code>
     */
    public Builder mergePixelFormat(info.malenkov.aspiabook.proto.PixelFormat value) {
      if (pixelFormatBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          pixelFormat_ != null &&
          pixelFormat_ != info.malenkov.aspiabook.proto.PixelFormat.getDefaultInstance()) {
          getPixelFormatBuilder().mergeFrom(value);
        } else {
          pixelFormat_ = value;
        }
      } else {
        pixelFormatBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.PixelFormat pixel_format = 3;</code>
     */
    public Builder clearPixelFormat() {
      bitField0_ = (bitField0_ & ~0x00000004);
      pixelFormat_ = null;
      if (pixelFormatBuilder_ != null) {
        pixelFormatBuilder_.dispose();
        pixelFormatBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.PixelFormat pixel_format = 3;</code>
     */
    public info.malenkov.aspiabook.proto.PixelFormat.Builder getPixelFormatBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getPixelFormatFieldBuilder().getBuilder();
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.PixelFormat pixel_format = 3;</code>
     */
    public info.malenkov.aspiabook.proto.PixelFormatOrBuilder getPixelFormatOrBuilder() {
      if (pixelFormatBuilder_ != null) {
        return pixelFormatBuilder_.getMessageOrBuilder();
      } else {
        return pixelFormat_ == null ?
            info.malenkov.aspiabook.proto.PixelFormat.getDefaultInstance() : pixelFormat_;
      }
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.PixelFormat pixel_format = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        info.malenkov.aspiabook.proto.PixelFormat, info.malenkov.aspiabook.proto.PixelFormat.Builder, info.malenkov.aspiabook.proto.PixelFormatOrBuilder> 
        getPixelFormatFieldBuilder() {
      if (pixelFormatBuilder_ == null) {
        pixelFormatBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            info.malenkov.aspiabook.proto.PixelFormat, info.malenkov.aspiabook.proto.PixelFormat.Builder, info.malenkov.aspiabook.proto.PixelFormatOrBuilder>(
                getPixelFormat(),
                getParentForChildren(),
                isClean());
        pixelFormat_ = null;
      }
      return pixelFormatBuilder_;
    }

    private int updateInterval_ ;
    /**
     * <pre>
     * Deprecated. Must be equal to 30.
     * </pre>
     *
     * <code>uint32 update_interval = 4;</code>
     * @return The updateInterval.
     */
    @java.lang.Override
    public int getUpdateInterval() {
      return updateInterval_;
    }
    /**
     * <pre>
     * Deprecated. Must be equal to 30.
     * </pre>
     *
     * <code>uint32 update_interval = 4;</code>
     * @param value The updateInterval to set.
     * @return This builder for chaining.
     */
    public Builder setUpdateInterval(int value) {

      updateInterval_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Deprecated. Must be equal to 30.
     * </pre>
     *
     * <code>uint32 update_interval = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpdateInterval() {
      bitField0_ = (bitField0_ & ~0x00000008);
      updateInterval_ = 0;
      onChanged();
      return this;
    }

    private int compressRatio_ ;
    /**
     * <code>uint32 compress_ratio = 5;</code>
     * @return The compressRatio.
     */
    @java.lang.Override
    public int getCompressRatio() {
      return compressRatio_;
    }
    /**
     * <code>uint32 compress_ratio = 5;</code>
     * @param value The compressRatio to set.
     * @return This builder for chaining.
     */
    public Builder setCompressRatio(int value) {

      compressRatio_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 compress_ratio = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCompressRatio() {
      bitField0_ = (bitField0_ & ~0x00000010);
      compressRatio_ = 0;
      onChanged();
      return this;
    }

    private int scaleFactor_ ;
    /**
     * <pre>
     * Deprecated. Must be equal to 100.
     * </pre>
     *
     * <code>uint32 scale_factor = 6;</code>
     * @return The scaleFactor.
     */
    @java.lang.Override
    public int getScaleFactor() {
      return scaleFactor_;
    }
    /**
     * <pre>
     * Deprecated. Must be equal to 100.
     * </pre>
     *
     * <code>uint32 scale_factor = 6;</code>
     * @param value The scaleFactor to set.
     * @return This builder for chaining.
     */
    public Builder setScaleFactor(int value) {

      scaleFactor_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Deprecated. Must be equal to 100.
     * </pre>
     *
     * <code>uint32 scale_factor = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearScaleFactor() {
      bitField0_ = (bitField0_ & ~0x00000020);
      scaleFactor_ = 0;
      onChanged();
      return this;
    }

    private int audioEncoding_ = 0;
    /**
     * <code>.info.malenkov.aspiabook.proto.AudioEncoding audio_encoding = 7;</code>
     * @return The enum numeric value on the wire for audioEncoding.
     */
    @java.lang.Override public int getAudioEncodingValue() {
      return audioEncoding_;
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.AudioEncoding audio_encoding = 7;</code>
     * @param value The enum numeric value on the wire for audioEncoding to set.
     * @return This builder for chaining.
     */
    public Builder setAudioEncodingValue(int value) {
      audioEncoding_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.AudioEncoding audio_encoding = 7;</code>
     * @return The audioEncoding.
     */
    @java.lang.Override
    public info.malenkov.aspiabook.proto.AudioEncoding getAudioEncoding() {
      info.malenkov.aspiabook.proto.AudioEncoding result = info.malenkov.aspiabook.proto.AudioEncoding.forNumber(audioEncoding_);
      return result == null ? info.malenkov.aspiabook.proto.AudioEncoding.UNRECOGNIZED : result;
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.AudioEncoding audio_encoding = 7;</code>
     * @param value The audioEncoding to set.
     * @return This builder for chaining.
     */
    public Builder setAudioEncoding(info.malenkov.aspiabook.proto.AudioEncoding value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000040;
      audioEncoding_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.info.malenkov.aspiabook.proto.AudioEncoding audio_encoding = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearAudioEncoding() {
      bitField0_ = (bitField0_ & ~0x00000040);
      audioEncoding_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:info.malenkov.aspiabook.proto.DesktopConfig)
  }

  // @@protoc_insertion_point(class_scope:info.malenkov.aspiabook.proto.DesktopConfig)
  private static final info.malenkov.aspiabook.proto.DesktopConfig DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new info.malenkov.aspiabook.proto.DesktopConfig();
  }

  public static info.malenkov.aspiabook.proto.DesktopConfig getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DesktopConfig>
      PARSER = new com.google.protobuf.AbstractParser<DesktopConfig>() {
    @java.lang.Override
    public DesktopConfig parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DesktopConfig> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DesktopConfig> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public info.malenkov.aspiabook.proto.DesktopConfig getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

