// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.address_book.proto

package info.malenkov.aspiabook.proto;

/**
 * Protobuf type {@code info.malenkov.aspiabook.proto.InheritConfig}
 */
public final class InheritConfig extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:info.malenkov.aspiabook.proto.InheritConfig)
    InheritConfigOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InheritConfig.newBuilder() to construct.
  private InheritConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InheritConfig() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new InheritConfig();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return info.malenkov.aspiabook.proto.AspiaAddressBook.internal_static_info_malenkov_aspiabook_proto_InheritConfig_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return info.malenkov.aspiabook.proto.AspiaAddressBook.internal_static_info_malenkov_aspiabook_proto_InheritConfig_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            info.malenkov.aspiabook.proto.InheritConfig.class, info.malenkov.aspiabook.proto.InheritConfig.Builder.class);
  }

  public static final int CREDENTIALS_FIELD_NUMBER = 1;
  private boolean credentials_ = false;
  /**
   * <code>bool credentials = 1;</code>
   * @return The credentials.
   */
  @java.lang.Override
  public boolean getCredentials() {
    return credentials_;
  }

  public static final int DESKTOP_MANAGE_FIELD_NUMBER = 2;
  private boolean desktopManage_ = false;
  /**
   * <code>bool desktop_manage = 2;</code>
   * @return The desktopManage.
   */
  @java.lang.Override
  public boolean getDesktopManage() {
    return desktopManage_;
  }

  public static final int DESKTOP_VIEW_FIELD_NUMBER = 3;
  private boolean desktopView_ = false;
  /**
   * <code>bool desktop_view = 3;</code>
   * @return The desktopView.
   */
  @java.lang.Override
  public boolean getDesktopView() {
    return desktopView_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (credentials_ != false) {
      output.writeBool(1, credentials_);
    }
    if (desktopManage_ != false) {
      output.writeBool(2, desktopManage_);
    }
    if (desktopView_ != false) {
      output.writeBool(3, desktopView_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (credentials_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, credentials_);
    }
    if (desktopManage_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, desktopManage_);
    }
    if (desktopView_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, desktopView_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof info.malenkov.aspiabook.proto.InheritConfig)) {
      return super.equals(obj);
    }
    info.malenkov.aspiabook.proto.InheritConfig other = (info.malenkov.aspiabook.proto.InheritConfig) obj;

    if (getCredentials()
        != other.getCredentials()) return false;
    if (getDesktopManage()
        != other.getDesktopManage()) return false;
    if (getDesktopView()
        != other.getDesktopView()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CREDENTIALS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCredentials());
    hash = (37 * hash) + DESKTOP_MANAGE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getDesktopManage());
    hash = (37 * hash) + DESKTOP_VIEW_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getDesktopView());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static info.malenkov.aspiabook.proto.InheritConfig parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiabook.proto.InheritConfig parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiabook.proto.InheritConfig parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiabook.proto.InheritConfig parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiabook.proto.InheritConfig parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiabook.proto.InheritConfig parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiabook.proto.InheritConfig parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiabook.proto.InheritConfig parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static info.malenkov.aspiabook.proto.InheritConfig parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiabook.proto.InheritConfig parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static info.malenkov.aspiabook.proto.InheritConfig parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiabook.proto.InheritConfig parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(info.malenkov.aspiabook.proto.InheritConfig prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code info.malenkov.aspiabook.proto.InheritConfig}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:info.malenkov.aspiabook.proto.InheritConfig)
      info.malenkov.aspiabook.proto.InheritConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return info.malenkov.aspiabook.proto.AspiaAddressBook.internal_static_info_malenkov_aspiabook_proto_InheritConfig_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return info.malenkov.aspiabook.proto.AspiaAddressBook.internal_static_info_malenkov_aspiabook_proto_InheritConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              info.malenkov.aspiabook.proto.InheritConfig.class, info.malenkov.aspiabook.proto.InheritConfig.Builder.class);
    }

    // Construct using info.malenkov.aspiabook.proto.InheritConfig.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      credentials_ = false;
      desktopManage_ = false;
      desktopView_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return info.malenkov.aspiabook.proto.AspiaAddressBook.internal_static_info_malenkov_aspiabook_proto_InheritConfig_descriptor;
    }

    @java.lang.Override
    public info.malenkov.aspiabook.proto.InheritConfig getDefaultInstanceForType() {
      return info.malenkov.aspiabook.proto.InheritConfig.getDefaultInstance();
    }

    @java.lang.Override
    public info.malenkov.aspiabook.proto.InheritConfig build() {
      info.malenkov.aspiabook.proto.InheritConfig result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public info.malenkov.aspiabook.proto.InheritConfig buildPartial() {
      info.malenkov.aspiabook.proto.InheritConfig result = new info.malenkov.aspiabook.proto.InheritConfig(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(info.malenkov.aspiabook.proto.InheritConfig result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.credentials_ = credentials_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.desktopManage_ = desktopManage_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.desktopView_ = desktopView_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof info.malenkov.aspiabook.proto.InheritConfig) {
        return mergeFrom((info.malenkov.aspiabook.proto.InheritConfig)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(info.malenkov.aspiabook.proto.InheritConfig other) {
      if (other == info.malenkov.aspiabook.proto.InheritConfig.getDefaultInstance()) return this;
      if (other.getCredentials() != false) {
        setCredentials(other.getCredentials());
      }
      if (other.getDesktopManage() != false) {
        setDesktopManage(other.getDesktopManage());
      }
      if (other.getDesktopView() != false) {
        setDesktopView(other.getDesktopView());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              credentials_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              desktopManage_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              desktopView_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean credentials_ ;
    /**
     * <code>bool credentials = 1;</code>
     * @return The credentials.
     */
    @java.lang.Override
    public boolean getCredentials() {
      return credentials_;
    }
    /**
     * <code>bool credentials = 1;</code>
     * @param value The credentials to set.
     * @return This builder for chaining.
     */
    public Builder setCredentials(boolean value) {

      credentials_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool credentials = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCredentials() {
      bitField0_ = (bitField0_ & ~0x00000001);
      credentials_ = false;
      onChanged();
      return this;
    }

    private boolean desktopManage_ ;
    /**
     * <code>bool desktop_manage = 2;</code>
     * @return The desktopManage.
     */
    @java.lang.Override
    public boolean getDesktopManage() {
      return desktopManage_;
    }
    /**
     * <code>bool desktop_manage = 2;</code>
     * @param value The desktopManage to set.
     * @return This builder for chaining.
     */
    public Builder setDesktopManage(boolean value) {

      desktopManage_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool desktop_manage = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDesktopManage() {
      bitField0_ = (bitField0_ & ~0x00000002);
      desktopManage_ = false;
      onChanged();
      return this;
    }

    private boolean desktopView_ ;
    /**
     * <code>bool desktop_view = 3;</code>
     * @return The desktopView.
     */
    @java.lang.Override
    public boolean getDesktopView() {
      return desktopView_;
    }
    /**
     * <code>bool desktop_view = 3;</code>
     * @param value The desktopView to set.
     * @return This builder for chaining.
     */
    public Builder setDesktopView(boolean value) {

      desktopView_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>bool desktop_view = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDesktopView() {
      bitField0_ = (bitField0_ & ~0x00000004);
      desktopView_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:info.malenkov.aspiabook.proto.InheritConfig)
  }

  // @@protoc_insertion_point(class_scope:info.malenkov.aspiabook.proto.InheritConfig)
  private static final info.malenkov.aspiabook.proto.InheritConfig DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new info.malenkov.aspiabook.proto.InheritConfig();
  }

  public static info.malenkov.aspiabook.proto.InheritConfig getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InheritConfig>
      PARSER = new com.google.protobuf.AbstractParser<InheritConfig>() {
    @java.lang.Override
    public InheritConfig parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<InheritConfig> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InheritConfig> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public info.malenkov.aspiabook.proto.InheritConfig getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

