// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.address_book.proto

package info.malenkov.aspiabook.proto;

public interface InheritConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:info.malenkov.aspiabook.proto.InheritConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool credentials = 1;</code>
   * @return The credentials.
   */
  boolean getCredentials();

  /**
   * <code>bool desktop_manage = 2;</code>
   * @return The desktopManage.
   */
  boolean getDesktopManage();

  /**
   * <code>bool desktop_view = 3;</code>
   * @return The desktopView.
   */
  boolean getDesktopView();
}
