// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.desktop.proto

package info.malenkov.aspiabook.proto;

public interface KeyEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:info.malenkov.aspiabook.proto.KeyEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 usb_keycode = 1;</code>
   * @return The usbKeycode.
   */
  int getUsbKeycode();

  /**
   * <code>uint32 flags = 2;</code>
   * @return The flags.
   */
  int getFlags();
}
