// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.desktop.proto

package info.malenkov.aspiabook.proto;

public interface PixelFormatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:info.malenkov.aspiabook.proto.PixelFormat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 bits_per_pixel = 1;</code>
   * @return The bitsPerPixel.
   */
  int getBitsPerPixel();

  /**
   * <code>uint32 red_max = 2;</code>
   * @return The redMax.
   */
  int getRedMax();

  /**
   * <code>uint32 green_max = 3;</code>
   * @return The greenMax.
   */
  int getGreenMax();

  /**
   * <code>uint32 blue_max = 4;</code>
   * @return The blueMax.
   */
  int getBlueMax();

  /**
   * <code>uint32 red_shift = 5;</code>
   * @return The redShift.
   */
  int getRedShift();

  /**
   * <code>uint32 green_shift = 6;</code>
   * @return The greenShift.
   */
  int getGreenShift();

  /**
   * <code>uint32 blue_shift = 7;</code>
   * @return The blueShift.
   */
  int getBlueShift();
}
