// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.desktop.proto

package info.malenkov.aspiabook.proto;

public interface RectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:info.malenkov.aspiabook.proto.Rect)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 x = 1;</code>
   * @return The x.
   */
  int getX();

  /**
   * <code>int32 y = 2;</code>
   * @return The y.
   */
  int getY();

  /**
   * <code>int32 width = 3;</code>
   * @return The width.
   */
  int getWidth();

  /**
   * <code>int32 height = 4;</code>
   * @return The height.
   */
  int getHeight();
}
