// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.desktop.proto

package info.malenkov.aspiabook.proto;

public interface SizeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:info.malenkov.aspiabook.proto.Size)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 width = 1;</code>
   * @return The width.
   */
  int getWidth();

  /**
   * <code>int32 height = 2;</code>
   * @return The height.
   */
  int getHeight();
}
