// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.key_exchange.proto

package info.malenkov.aspiabook.proto;

public interface SrpServerKeyExchangeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:info.malenkov.aspiabook.proto.SrpServerKeyExchange)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes number = 1;</code>
   * @return The number.
   */
  com.google.protobuf.ByteString getNumber();

  /**
   * <code>bytes generator = 2;</code>
   * @return The generator.
   */
  com.google.protobuf.ByteString getGenerator();

  /**
   * <code>bytes salt = 3;</code>
   * @return The salt.
   */
  com.google.protobuf.ByteString getSalt();

  /**
   * <code>bytes B = 4;</code>
   * @return The b.
   */
  com.google.protobuf.ByteString getB();

  /**
   * <code>bytes iv = 5;</code>
   * @return The iv.
   */
  com.google.protobuf.ByteString getIv();
}
