// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.common.proto

package info.malenkov.aspiabook.proto;

public interface VersionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:info.malenkov.aspiabook.proto.Version)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 major = 1;</code>
   * @return The major.
   */
  int getMajor();

  /**
   * <code>uint32 minor = 2;</code>
   * @return The minor.
   */
  int getMinor();

  /**
   * <code>uint32 patch = 3;</code>
   * @return The patch.
   */
  int getPatch();

  /**
   * <code>uint32 revision = 4;</code>
   * @return The revision.
   */
  int getRevision();
}
